### PR TITLE
Add some tooltip for devtool view

### PR DESCRIPTION
**Pull request by yfdyh000**
A minor flaw, the "Max" is not retrieve and process the `requestLogMaxEntries: 1000`.

### CODE REVIEW

**Comment by yfdyh000** [comment]
@gorhill Updated.

**Comment by debugzxcv** [comment]
[Looks like logger has changed.](https://github.com/gorhill/uBlock/commit/f9652b5f574d06627941af69388ba136c7ae857e) Is there any update?

**Comment by yfdyh000** [comment]
I have uploaded it twice, but did not get any support or opposition. updating it is a tedious process :(

**Comment by debugzxcv** [comment]
@gorhill What do you think?

**Comment by gorhill** [comment]
Declined.

**Pull request closed without merging**
