### PR TITLE
loseless image compression

### PR DESCRIPTION
**Pull request by michal-gski**
saved 6.7KB out of 18,2 KB (36.7%)

### CODE REVIEW

**Comment by Hrxn** [comment]
Pngcrush?

**Comment by LifeIsStrange** [comment]
I think if That's useful, but FLIF is new and the Best lossless image compression codec. 
http://flif.info/

**Comment by TPS** [comment]
@LifeIsStrange You're probably trolling, but FLIF is useless for this application as there's no native browser support!

**Comment by Kromka** [comment]
You can even compress more with tinpng service

**Comment by Hrxn** [comment]
I guess you mean this one: https://tinypng.com/

**Comment by LifeIsStrange** [comment]
TPS I was not trolling :m That's for the pictures of the pull request. 


And tinypng is not lossless.

**Comment by TPS** [comment]
@LifeIsStrange Ok, how do you plan to integrate FLIF images into uBlock instead of better-optimizing the PNGs here?

@All Anyone try [FileOptimizer](http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer)?  I find it's _very_ close to the best I can do manually (& losslessly) otherwise, & @javiergutierrezchamorro is a _hugely_ responsive dev. :smile: Download _(very clean)_ Windows binaries @ [SourceForge](http://www.sourceforge.net/projects/nikkhokkho/files/FileOptimizer).

**Comment by javiergutierrezchamorro** [comment]
As discused @LifeIsStrange there are for sure better image codecs than PNG: webp, FLIF, BPG, ...But FileOptimizer philosophy is not being a format converter, but a lossless optimizer.

@TPS thank you very much for your kind comments.

**Comment by gwarser** [comment]
https://github.com/chrisaljoudi/uBlock/pull/1274

**Comment by gorhill** [comment]
> saved 6.7KB out of 18,2 KB (36.7%)

The whole package (Firefox) is 1450,9 KB. So it's more like:

"saved 6.7KB out of 1450,9 KB (<0.5%)"

**Comment by gwarser** [comment]
Images _may_ compress better inside extension package (.zip) when no png compression is applied.

**Comment by TPS** [comment]
@javiergutierrezchamorro You're welcome! :bow:

@gorhill This is true, even if folks are using space-optimized builds, but this kind of PR is _very_ rare (probably 1-time), & is actually helpful for those of us on metered connections, in that it saves a little on _every_ update.

@gwarser That PR @ that abandonware does _this_ project no good, unless in the unlikely event the images are the same.  I thought @chrisaljoudi reskinned somewhat after "acquiring" the uBlock name.  Also, uncompressed PNGs _rarely_ compress better inside XPIs (ZIP-based) than those optimized properly, because of the [powerful PNG filtering](http://www.libpng.org/pub/png/book/chapter09.html#png.ch09.div.1) that ZIP lacks.

**Comment by TPS** [comment]
@gwarser What toolchain did you use for the results [above](#issuecomment-221863333)?

**Comment by gwarser** [comment]
I use Gimp to create uncompressed png. Others are from this repo and pull request. Package (.xpi) is created on Linux Mint.
As you say, uncompressed images are 105 bytes bigger.

**Comment by XhmikosR** [comment]
You should use zopfli too, if you are going lossless only.

**Pull request closed without merging**
