### PR TITLE
#2433 Changed the XML namespaces to please jpm sign

### PR DESCRIPTION
**Pull request by andreicristianpetcu**

### CODE REVIEW

**Comment by gorhill** [comment]
Q: did you try if the resulting xpi can be successfully dropped into Pale Moon, Sea Monkey?

**Comment by andreicristianpetcu** [comment]
Yes. This is what I ran:

Firefox - legacy
```bash
./tools/make-firefox.sh
# vim dist/build/uBlock0.firefox/install.rdf to edit a new ID in install.rdf since I don't own your addon and I cannot sign it
jpm xpi --addon-dir dist/build/uBlock0.firefox/
jpm sign --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET --xpi dist/build/uBlock0.firefox/null.xpi
```
Firefox - webextension
```bash
./tools/make-webext.sh
# vim dist/build/uBlock0.webext/install.rdf to edit a new ID in install.rdf since I don't own your addon and I cannot sign it 
jpm xpi --addon-dir dist/build/uBlock0.webext/
jpm sign --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET --xpi dist/build/uBlock0.firefox/null.xpi
```
I tested the result legacy addon from ublock_origin-1.11.3b1-an+fx+sm+tb.xpi in Pale Moon 27.1.2 (64-bit), Tor 6.5 (based on Mozilla Firefox 45.7.0), Tor 6.5.1 (based on Mozilla Firefox 45.8.0), GNU IceCat v45.7.0, Firefox Nightly 55.0a1 (2017-03-09) (64-bit). I'm sorry I do not have Sea Monkey installed and the installation failed on my Fedora for some reason. But here are the two generated builds so you can test.
[Here is the legacy](https://andreicristianpetcu.github.io/chrome2firefox/addons/legacy_signed/ublock_origin-1.11.3b1-fx.xpi) and [the embeded WebExtension](addons/legacy_signed/ublock_origin-1.11.3b1-fx.xpi). There is the old Seamonkey metadata in the install.rdf so I guess it still works. Sorry for not testing it on this browser.
Hope all is fine :)

**Comment by andreicristianpetcu** [comment]
HA! Made Seamonkey work! There is some strange issue with the button in the preferences on all browsers. I think this might be due to the addon ID change. Do you have any clue what might be the cause of this?

screenshot from 2017-03-10 01-40-04

**Comment by onetwothreefall** [comment]
> There is some strange issue with the button in the preferences on all browsers. I think this might be due to the addon ID change. 

The ID is hard-coded in `platform/firefox/vapi-background.js` (search for `optionsObserver`) so for a custom build, you'll need to change it there too.

**Comment by andreicristianpetcu** [comment]
I don't want a custom build with this fix (I have a bookmar pointing to the uBloc Origin settings page). I just wanted to make sure I did not break anything :D

**Comment by gorhill** [comment]
Thanks your contribution.

**Pull request merged**
