### PR TITLE
Round hour up to nearest day

### PR DESCRIPTION
**Pull request by jspenguin2017**
https://github.com/uBlockOrigin/uBlock-issues/issues/41#issuecomment-389467010

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks.

**Comment by gwarser** [comment]
I just greped my dump of filterlist.com from october 2017:

#### !Expires after 5 days
https://easylist-downloads.adblockplus.org/bulgarian_list+easylist.txt (two lines)
https://stanev.org/abp/adblock_bg.txt

#### !! Expires: 10 days
http://blogram.net/wp-content/uploads/easylist4.txt (and other BLOGRAM, probably outdated)

#### ! Expires: 1d
https://easylist-downloads.adblockplus.org/malwaredomains_full.txt

#### ! This list expires after 6 days
https://fanboy.co.nz/fanboy-antifacebook.txt
https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fake-news.txt
https://fanboy.co.nz/fanboy-antifonts.txt
https://fanboy.co.nz/fanboy-cookiemonster.txt
https://fanboy.co.nz/enhancedstats.txt
https://fanboy.co.nz/israelilist/IsraelList.txt

#### !    This list expires after 5 days (extra spaces)
https://raw.githubusercontent.com/mozillahispano/nauscopio-filtros/master/filtros.txt (probably outdated)

**Comment by jspenguin2017** [comment]
Eh... How does ABP and Adguard parse them?

**Comment by jspenguin2017** [comment]
OK, I found it: https://github.com/adblockplus/adblockpluscore/blob/ec65d0a80470fc2eacd9ef83ec19cd3204f0b8db/lib/synchronizer.js#L148

ABP clearly won't parse `!Expires after 5 days`, `!! Expires: 10 days`, not `! This list expires (etc)`. 
I still need to investigate `! Expires: 1d`. 

Note that ABP does accept `! Expires : 3 days` but uBO won't. ABP's RegExp is: 
image

**Comment by jspenguin2017** [comment]
Indeed, `! Expires: 1d` and `! Expires: 12h` are valid in ABP. 
```js
    let expirationInterval = DEFAULT_EXPIRATION_INTERVAL;
    if (params.expires)
    {
      let match = /^(\d+)\s*(h)?/.exec(params.expires);
      if (match)
      {
        let interval = parseInt(match[1], 10);
        if (match[2])
          expirationInterval = interval * MILLIS_IN_HOUR;
        else
          expirationInterval = interval * MILLIS_IN_DAY;
      }
    }
```

**Comment by gorhill** [comment]
So "day" is assumed unless there is "h". Make sense.

**Pull request merged**
