### PR TITLE
small captalization

### PR DESCRIPTION
**Pull request by ialexsilva**

### CODE REVIEW

**Comment by gwarser** [comment]
Draft of new description is posted here https://github.com/uBlockOrigin/uBlock-issues/wiki/Reference-description-of-uBO-in-various-extensions-stores

**Comment by gorhill** [comment]
Thanks.

The wiki page is to come up with a new official description -- I had forgotten about it. The idea is that people better in English then I am can improve it.

**Comment by gwarser** [comment]
Maybe you can post it on Crowdin as new file and send "request for comments" message?

**Comment by gorhill** [comment]
Turns out translation plain text file on Crowdin is really bad: each time I want to update the file, the translation for the modified paragraphes are lost, there is no option to keep the current translation even if only one tiny word changed in one of the paragraph.

**Comment by gwarser** [comment]
No way to upload "Description_v2.txt" and keep "Description.txt" untouched?

**Comment by gorhill** [comment]
Sure, but the primary issue of not being able to update with losing translations is still there.

I looked a bit more into crowdin options, and I think the description would need to be CSV-based for proper update, which means I will need to convert the description into a CSV (the first field being a key, the second being the paragraph), and I would need a script to convert the CSV into pure text for when I want to actual use the description.

**Pull request merged**
