### PR TITLE
01net.com added

### PR DESCRIPTION
**Pull request by HLFH**
01net.com provides adwares and spywares on www.01net.com/telecharger/ (see sources here: https://github.com/gorhill/uBlock/wiki/Badware-risks).

### CODE REVIEW

**Comment by HLFH** [comment]
Hi @gorhill! So do you think it's a good idea to merge this PR to the badware.txt file? Any comments? ;)

**Comment by gorhill** [comment]
I need to research a lot more first. Whatever appears in `badware.txt`, I will be the one who has to defend why it's in there, so I must myself be personally convinced something has to be in there, and for this, I must research the issue myself. I did not research yet, I will and I get the time.

**Comment by HLFH** [comment]
@gorhill The alternative would be that uBlock Origin support **partial strict blocking**, for example here, we could **strictly block the malicious category**: *http://www.01net.com/telecharger/* and not the whole site. Do you think we could add the feature to uBlock?

**Comment by gorhill** [comment]
> Do you think we could add the feature to uBlock? 

It's already supported, I added this in 1.0.0.0 in order to be able to add `http://tucows.com/download` when I decide to do so. The trick is to use the `document` filter option (which works only for a blocking filter):

    ||www.01net.com/telecharger/$document

This will trigger strict blocking.

**Comment by HLFH** [comment]
@gorhill Thanks a lot! Because [01net.com is also a well-known IT news website in France](https://fr.wikipedia.org/wiki/01net.com), I could say the partial strict blocking is better for 01net.com. You could see on the [Wikipedia page](https://fr.wikipedia.org/wiki/01net.com) that the badware issue is only related to the /telecharger/* category:

**Comment by HLFH** [comment]
Hi @gorhill. Any news? Thanks.

**Comment by gorhill** [comment]
Sorry forgot about this. I will add `||www.01net.com/telecharger/$document`, I think there are enough reference material to support this. For `macupdate.com` I have only two reference entries, more would be better.

Also, I rather add them myself because:

- The `checksums.txt` file always need to be regenerated after any change to uBO's filter lists.
- Tidiness: entries are ordered by base domain name in _Badwares risks_ file.

**Comment by HLFH** [comment]
@gorhill I could also do a new PR with:
- modified badware.txt with the 01.net.com/telecharger/$document strict blocking added
- modified checksums.txt with the new MD5 checksum of badware.txt
- respect of base domain name order in badware.txt

And I could find [some new links](https://github.com/gorhill/uBlock/wiki/Badware-risks) for macupdate.com for a new PR in a few months.

**Comment by gorhill** [comment]
> I could also do a new PR with:

Sorry, I already added `01.net` in the mean time.

**Comment by HLFH** [comment]
I saw that. Thanks for the commit. I love what you've done for the web. Thanks.

**Pull request closed without merging**
