### PR TITLE
Add tests for SNFE initialization

### PR DESCRIPTION
**Pull request by mjethani**
These are tests for `StaticNetFilteringEngine.create()`.

### CODE REVIEW

**Comment by gorhill** [comment]
Sorry, I moved `platform/nodejs/tests/snfe.js` to `platform/npm/tests/snfe.js`.

I wanted to be able to run local tests in node purely for investigation purpose without having to pull all external dependencies from mocha/eslint and whatever may be required in the future.

**Comment by mjethani** [comment]
@gorhill that's cool.

Let me rebase the patches.

**Comment by mjethani** [comment]
Since there's a `dig` target now, I think maybe you should try to use that one in `.github/workflows/main.yml`.

For `package.json` you could do something like so:

```bash
node -pe 'a=require("package.json");delete a.devDependencies;JSON.stringify(a)'
```

This would give you exactly the same `package.json` file but without the `devDependencies` field. In the published version of the package, there won't be any `devDependencies` field in the `package.json` file. And this should make it just like before as far as the published version is concerned.

**Comment by gorhill** [comment]
For the `dig` target, I removed the `rm -rf` command to remove the build and start from scratch, as I want to keep generated data files around -- because of this I think it's best to stick with the `npm` one. What's the best practices for npm packages? Are they usually published with their test suites?

**Comment by mjethani** [comment]
> What's the best practices for npm packages? Are they usually published with their test suites?

I'm not sure what the best practice is, and I imagine most people simply ship the tests as well, even though `npm install` won't install the development dependencies for a package and the intent is not for anyone using the package to also runs the tests.

The way to ignore the `tests` directory as well as the new `results.json` file (https://github.com/gorhill/uBlock/pull/3828) is to add these to `.npmignore`. This way `npm pack` will not include them in the archive.

**Pull request merged**
