### PR TITLE
Thunderbird: Fix closing extension tabs

### PR DESCRIPTION
**Pull request by M-Reimer**
This patch fixes the functions, needed to make the "Close extension tabs" code work when closing Thunderbird.

I hope this doesn't make more stuff working than expected (and so causes errors in cases, where I've not found them so far).

I've also adapted the loop to loop over the tabs. This may also fix a bug on Firefox where some extension tabs get restored on next start if more than one dashboard or logger tab is opened (which is actually possible at least from Addons manager).

### CODE REVIEW

**Comment by gorhill** [comment]
Why were lines 1164-1165 changed?

**Comment by M-Reimer** [comment]
I've created a small example to find out why the existing code does not work well:

http://js.do/code/70121
The code creates a random array and then removes all items starting with "A" once with the "walk from the end" and once with "for of".

The list of tabs is just an array of items. If we remove items from arrays (that's what happens if we close tabs), then the length of the array changes and indexes move position and actually point to different items as they did before removing an item. Walking an array from the end is a common way to do this. Even if the last index gets invalid, this is no problem, as with the next iteration, we move one to the left anyway.

In fact all those new fancy javascript features often cause much trouble, at least in my experience. I prevent using the "new features" wherever possible. They look nice, but you don't know what's happening behind the scenes.

**Comment by gorhill** [comment]
> In fact all those new fancy javascript features often cause much trouble

I would say I agree in general. The problem here is something I didn't realize, the array could be "live" and the `removeTab()` in there could modifies it on the fly. Good catch.

**Comment by gorhill** [comment]
Question: can the [code at line 986](https://github.com/gorhill/uBlock/blob/557f6611b50c4416c422a1224c259ed994346e68/platform/firefox/vapi-background.js#L986) ever be executed for Thunderbird?

**Comment by M-Reimer** [comment]
I think this depends on which types of object you usually pass to this function. So far I don't understand every aspect on how uBlock Origin works in detail.

**Pull request merged**
