### PR TITLE
Add piperun's IPlogger filterlist

### PR DESCRIPTION
**Pull request by piperun**
It should work, unfortunately can't test it.

### CODE REVIEW

**Comment by ddraws** [comment]
Better submit an issue.
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit

**Comment by piperun** [comment]
Will do.

**Comment by diego898** [comment]
I see there is now https://github.com/uBlockOrigin/uAssets/issues/296 corresponding to the pull request on this repo. Is this the desired state for this?

**Comment by gorhill** [comment]
I can't keep adding entries to the _3rd-party filters_ pane, it has already grown probably beyond what would be optimal. Your list is listed at filterlists.com, and uBO's wiki link to that page for those who wants more choice of lists.

**Pull request closed without merging**
