### PR TITLE
added baixaki.com.br

### PR DESCRIPTION
**Pull request by ialexsilva**
http://baixaki.com.br is a site like softonic.com brings the adware on installers

### CODE REVIEW

**Comment by ialexsilva** [comment]
Example link @gorhill: http://www.baixaki.com.br/download/ccleaner.htm 
click on Baixar(Download) and you download software installer with adware and bundleware...

**Comment by anewuser** [comment]
Baixaki is the largest downloads site in Brazil. If you block it, people will just uninstall uBlock Origin.

It's a smarter idea to hide the button to download their customized installer and leave out only the "baixar sem instalador" direct link.

**Comment by ialexsilva** [comment]
@anewuser Remid the user have a power to disable strict blocking...

**Comment by ialexsilva** [comment]
updated: http://www.baixaki.com.br showing unsafe alert on chrome and firefox
@gorhill  add this to badware list

**Comment by vgturtle127** [comment]
@ialexsilva @gorhill doesn't accept pull requests. :disappointed: 

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit

**Comment by gorhill** [comment]
Closing: need to have more good source for [baixakicombr-candidate](https://github.com/gorhill/uBlock/wiki/Badware-risks#baixakicombr-candidate).

**Pull request closed without merging**
