### PR TITLE
allow scripts to run with bash in other locations

### PR DESCRIPTION
**Pull request by qbit**
This lets me run the tool scripts on OpenBSD and other *nix boxes with bash in a different location.

### CODE REVIEW

**Comment by martinrotter** [comment]
No problem, looks good. :)

**Comment by vgturtle127** [comment]
@qbit @martinrotter @gorhill doesn't accept pull requests. :disappointed: 

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#before-you-submit

**Comment by gorhill** [comment]
Closing, as after reading about `#!/usr/bin/env bash`, I understand that this is not possible to pass more than one argument to the shell script -- which means `./tools/make-firefox.sh all rc0` would no longer work.

**Comment by gwarser** [comment]
```
on@pc:~ > more test.sh
#! /usr/bin/env bash

echo "$1"
echo "$2"
echo "$3"

on@pc:~ > ./test.sh asdf qwer zcvb
asdf
qwer
zcvb
on@pc:~ >
```

**Comment by gorhill** [comment]
I see... What did the comment _"you can't pass an additional argument"_ referred to in one of the comments to [this post](http://stackoverflow.com/a/16365367)?

**Comment by gwarser** [comment]
Probably:

`#! /usr/bin/env bash +O globstar`

will not work

**Comment by qbit** [comment]
The claim that full path declaration is more secure is totally false too.. If someone has access to your system to put a shell script in some directory that is in your path, they also have the ability to set an alias: `alias /bin/bash=/usr/local/bin/hacked_bash` would be one "workaround" an attacker could use.

**Comment by gorhill** [comment]
Ok I just cherry-picked your first commit, there were subsequent commits which were causing merge conflicts (the webrtc-related changes). Thanks for the fix.

**Comment by qbit** [comment]
:+1: Thanks!

**Pull request closed without merging**
