### PR TITLE
Add instruction for Ru AdList

### PR DESCRIPTION
**Pull request by mikhaelkh**
Ru AdList has many additions to block ads, counters, annoyances, anti-adblock warnings in Russian websites. This page contains the guide to all of them.

### CODE REVIEW

**Comment by gorhill** [comment]
Your change would break uBO. Use a JSON linter before modifying `assets.json`.

**Comment by mikhaelkh** [comment]
Fixed.

**Comment by gorhill** [comment]
Thanks.

**Comment by gotitbro** [comment]
@gorhill I was going to open a separate thread but might as well ask here. uBO currently supports some Adguard filter syntax while some important syntax such as script blocking etc. are left out. These are extremely useful for nefarious websites which are increasing everyday.

I noticed that enabling the **_Russian Adguard Filter_** (which is based on **_RU Adlist_**) in uBO itself still let many ads through on the aforementioned nefarious websites due to the fact that uBO does not support the syntax of some filters.

So, I would like to ask you this do you plan to support further Adguard syntax? It would prove really useful for users.

**Comment by gorhill** [comment]
I don't want filter list authors to be able to inject arbitrary javascript into web pages, the only scriptlets injected by uBO will be the ones vouched for by the project.

Adguard's approach is not going to be accepted for AMO, they might have to go uBO's way, in which case sharing efforts would make sense.

**Comment by gorhill** [comment]
> Russian Adguard Filter (which is based on RU Adlist

I don't think this is true. If you enable only both these lists in uBO, there is little overlap:

    RUS: Adguard Russian Filter​: ​​​​18,024 used out of 18,063
    RUS: RU AdList: 19,326 used out of 21,724

**Comment by gotitbro** [comment]
@gorhill I was already thinking that the JS injections might not be considered appropriate but we can't deny they are effective.

> Adguard's approach is not going to be accepted for AMO

But they already have their extension approved there. Did some policies change?

> I don't think this is true. If you enable only both these lists in uBO, there is little overlap

Interesting, I guess it was initially based on RU Adlist but not anymore 😕. Any insight @Alex-302?

**Comment by gorhill** [comment]
> Did some policies change?

I can only say that on my side, this is what happened: <https://github.com/gorhill/uBlock/commit/126110c9a0a0630cd556f5cb215422296a961029>.

**Comment by Alex-302** [comment]
@gotitbro 
> Russian Adguard Filter (which is based on RU Adlist)

it is not based on RU Adlist. It was a long time ago(more than 5-7 years ago) and not true at the moment:) Now our Russian filter and RuAdList - two different filters. Our filter at least not worse than RuAdList.

**Comment by mikhaelkh** [comment]
@gorhill also you may consider moving BitBlock to Annoyances because its goal is to remove annoyances and it includes rules not only for Russian websites.

**Comment by gorhill** [comment]
I think I will remove BitBlock, especially after you added the instruction URL for "RU AdList", this means the list still has good visibility for Russian users.

**Comment by mikhaelkh** [comment]
I agree, especially because of this in BitBlock description:
```
! Подписка предназначена для тех, кто не желает всего этого видеть и
! НЕ РЕКОМЕНДУЕТСЯ к установке по умолчанию.
```
In English:
```
!Subscription is for those who do not want to see all this and
!NOT RECOMMENDED for the default installation.
```

**Comment by gotitbro** [comment]
@mikhaelkh Can you tell me what the instruction URL contains? Thanks.

@gorhill But why remove it completely? We already have a Chinese annoyance list wouldn't it be better to just rename the list BitBlock Annoyance list? 

I think uBO is a great resource for people to discover lists that have already been vetted by the community. Makes sense if we have good lists listed here.

**Comment by mikhaelkh** [comment]
@gotitbro use the power of Google Translate :)

**Comment by mikhaelkh** [comment]
@gorhill you should list that BitBlock had been removed in [Releases](https://github.com/gorhill/uBlock/releases)

**Comment by gotitbro** [comment]
> use the power of Google Translate :)

@mikhaelkh If only that would've helped not getting understandable translation.

**Comment by mikhaelkh** [comment]
@gotitbro mainly for Russian websites.
[RU AdList](https://easylist-downloads.adblockplus.org/advblock.txt) - ads
[RU AdList CSS Fixes](http://userstyles.org/styles/101141/ru-adlist-css-fixes) - userstyle for Stylish
[RU AdList JS Fixes](https://greasyfork.org/ru/scripts/19993-ru-adlist-js-fixes) - userscript for Tampermonkey
[Counters](https://easylist-downloads.adblockplus.org/cntblock.txt) - counters
[BitBlock](https://easylist-downloads.adblockplus.org/bitblock.txt) - annoyances
[Anti-adblock](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt) - Adblock Warning Removal List

**Pull request merged**
