### PR TITLE
Request to add mypdns.(org|com)

### PR DESCRIPTION
**Pull request by spirillen**
As many users are using out lists in there adblockers, we would like to help them making it easier to subscribe to our lists

Not at least from the linking tools:

```python
abp:subscribe?location=
```

### CODE REVIEW

**Comment by gorhill** [comment]
You are not providing any example of a page which contains the links to subscribe to. When visiting `mypdns.com`, this leads to a certificate error. When visiting `mypdns.org`, I see no obvious link to a list.

You reformatted the modified files such that the every line in the  files are shown as having changed.

**Comment by spirillen** [comment]
> You are not providing any example of a page which contains the links to subscribe to. When visiting `mypdns.com`, this leads to a certificate error. When visiting `mypdns.org`, I see no obvious link to a list.
> 

Crossed my mind after posting this text.

Here is the Old layout which will be subject for change to include individual list if you accept this PR

https://mypdns.org/adblocker-rules/index.htm (Changing to `https://mypdns.org/adblocker-rules/index.php` some time)

> You reformatted the modified files such that the every line in the files are shown as having changed.

VSCode did that, I can rewind it if you prefer it the other way

**Comment by gorhill** [comment]
You should simply instruct visitor to right-click the link then select "Subscribe to filter list..." to import the list into uBO, this works without requiring any change to the repo here. I prefer that approach.

**Comment by spirillen** [comment]
Could do that as well.

Non the less I would be a happy man if this got merged

**Pull request closed without merging**
