### PR TITLE
Fix #2493 by using the createWindowlessBrowser API when available

### LINKED ISSUE #2493: uBO broken on Firefox mozilla-central tip
This hasn't shipped in a nightly build yet since it was merged to mozilla-central after the 2017-03-31 nightlies were created, but bug 1145470 has broken uBO (won't even load).

The error in the browser console is:
Security Error: Content at resource://gre-resources/hiddenWindow.html may not load or link to chrome://ublock0/content/background.html#1.11.4.

### PR DESCRIPTION
**Pull request by gorhill**

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks for the fix.

I suppose a similar fix is needed for [uMatrix](https://github.com/gorhill/uMatrix)?

Would you be willing to submit of pull request for uMatrix as well?

**Comment by gorhill** [comment]
@gijsk Thanks for the fix.

I suppose a similar fix is needed for [uMatrix](https://github.com/gorhill/uMatrix)?

Would you be willing to submit of pull request for uMatrix as well?

**Comment by gijsk** [comment]
I can try to have a look at uMatrix, might be tomorrow or Monday before I get to it though. It looks like its bootstrap.js is subtly different from the one for uBlock Origin, and at a glance, like the one from uBlock Origin might have more recent fixes (specifically, the timer isReady check for the hidden window)? In that case, it might be simplest to just copy the current bootstrap.js from uBlock Origin and re-replace the hostName, unless there's bits that I missed?

**Comment by gorhill** [comment]
> I can try to have a look at uMatrix, might be tomorrow or Monday before I get to it though.

Ok, in that case I will import your fix, as this is currently breaking uMatrix for users on Nightly.

**Pull request merged**
