### PR TITLE
Adds ROad Block as a Romanian third party filter.

### PR DESCRIPTION
**Pull request by tcptomato**
Hey,

Since I got fed up with the existing Romanian list ( I think you had the same issues with it, in this pull request https://github.com/gorhill/uBlock/pull/974 ), I created a new, stricter one. For the moment it's pretty small, but I'll keep on expanding it.

Thanks,

Tom

### CODE REVIEW

**Comment by tcptomato** [comment]
@gorhill  Sorry. I just noticed you don't want pull requests ( i was using a previous contribution as a precedent). What is the process to submit a list for your consideration  to be included into ubo. If there is none please close this.

**Comment by gorhill** [comment]
I pulled the changes locally because there were merge errors, following instructions provided by GitHub, and somehow it appears the authorship of the changes has been lost in the process -- sorry about this.

**Comment by tcptomato** [comment]
No problem. I had my own share of weird merge errors. Thanks for the merge.

**Comment by ryanbr** [comment]
Not a great filterlist, mixing trackers and social elements with ads in a list. also /banners/* /banner/* /ads/* /Ads/* will cause false positives.

**Comment by tcptomato** [comment]
I removed the offending filters. Hope this is more to your liking.

**Comment by ryanbr** [comment]
I was expecting more Romanian related filters, seems to be mostly generic trackers?

**Comment by tcptomato** [comment]
Most romanian ones are in the list. If you know one I missed, please share. The generic ones are ones used on major sites, which weren't always filtered in abp.

**Comment by ryanbr** [comment]
Most of these trackers should be taken care of by Easyprivacy, which wouldn't leave much of a list if removed. Why not just submit the missing Romanian sites to the list ro authors to fix up?

**Comment by tcptomato** [comment]
Because the Romanian author is a guy globally whitelisting the ad sites he uses on his website and will never do that. This is the reason the original Romanian list was removed from uBO. 

Easyprivacy comes from a company that thinks there are acceptable ads. I would like to avoid to find out what acceptable tracking looks like.

**Comment by ryanbr** [comment]
Easyprivacy and Easylist is maintained separately from Eyeo/Adblock plus.

**Comment by tcptomato** [comment]
But are hosted on a domain owned by Eyeo. They could hijack it any time, but this is secondary. 

The Easylist policy says that "Filters should only be added for English websites; supplements support other languages.". The Romanian supplement maintainer is the person I mentioned in my last reply.

**Comment by ryanbr** [comment]
Easprivacy (trackers) will block international/non-english sites. And its very unlikely Eyeo will hijack anything, its treated separately to avoid a conflict of interest.

**Comment by tcptomato** [comment]
Sent the missing ones to easyprivacy. Will check tomorrow if I skipped anything. Unlikely isn't impossible.

**Comment by tcptomato** [comment]
@gorhill  Happy with the changes ?

**Comment by ryanbr** [comment]
With the trackers removed, there wouldn't be much a list left.

**Comment by tcptomato** [comment]
Is there a minimum size specified I didn't see? I don't see the issue as long as it blocks the regional stuff that isn't included in other places.

**Comment by ryanbr** [comment]
While there isn't a limit on list size,  calling this list a Romanian list without blocking that many actual .ro ads seems deceptive.  I know your head is in right place,  and you want to create an alternative list but it needs to mature (as in cover more Romanian sites) so it can be more useful.

**Comment by tcptomato** [comment]
I took it as romanian in the sense it covers the crap used on romanian sites, not stuff hosted in Romania.

**Comment by gorhill** [comment]
Let it mature, time will tell. If it ends up becoming de facto list for Romanians, I will include it, assuming it is still actively maintained. It was completely my mistake to include it immediately.

**Comment by IDKwhattoputhere** [comment]
> globally whitelisting the ad sites he uses

The ads on his site load from

    https://profitshare.ro/j/jXY
and

    http://e-day.ro/api/produs125x125.php
which are not whitelisted but also not blocked.
Your list breaks sites e.g. e-day.ro
You should also add the missing ads on nwradu.ro

**Comment by arthurtiteica** [comment]
Common guys. We have no good Romanian lists. tcptomato is trying to start one. Instead of complaining about it maybe you could submit an issue or a pull request.

**Comment by tcptomato** [comment]
The ads on his site are blocked by a div rule. But `@@||profitshare.emag.ro/get_ads.php?*`
`@@||profitshare.ro/get_ads.php?*` are whitelisted.

**Comment by IDKwhattoputhere** [comment]
You claimed he was globally whitelisting the advertisers which he uses which is false.

**Comment by tcptomato** [comment]
He uses the advertiser on his site. Has two whitelist rules. ( the fact that he needed a whitelist means that it's blocked by some other rule).  Now on his personal site the ad is filtered by some other rule. This doesn't change the fact that his rule allows the ads of profitshare (with whom he has a business relationship)  to run on other sites due to his whitelist. What exactly is false here?

**Comment by IDKwhattoputhere** [comment]
The ads of profitshare are not whitelisted on his site. You said he whitelists those ads globally (aka on all sites).

**Comment by tcptomato** [comment]
If the things in the link from your comment ( https://github.com/tcptomato/ROad-Block/issues/1 ) are true, I need to apologise to zoso for accusing him of something he didn't do. But it's very  stupid to use a script called get_ads for other purposes.

**Comment by tcptomato** [comment]
Globally also has a meaning of most of the world with an insignificant number of exceptions. For example here http://www.mastercard.com/global/. They call themselfs a global payments solution company, but they won't work in North Korea for example.

**Comment by IDKwhattoputhere** [comment]
He still does for some reason not block all ads he knows of (e-day.ro on his website for example) so I have to give you at least some credit.

> Globally also has a meaning of most of the world

True, I did not think about it that way.

**Comment by zosoro** [comment]
some guys, geez, are so blind in their hate of me, they make such stupid mistakes. 
i mean, look at that list. so much hate. how hateful you have to be to start a list which blocks a banner that is shown only on two blogs? really?

**Comment by tcptomato** [comment]
I think you have an ego problem. Not all people hate you, or care that much about you.
And it's not a stupid mistake, it is a honest one. If you don't know the difference that's your problem.

And what exactly is the threshold for blocking a banner, how many websites? And an ad is an ad. Your position is hypocritical, since you run your own list.

**Comment by zosoro** [comment]
dude, u created a list just to block my stuff. come on, what ego, it shows right there the purpose of the list. and then u copied the domains of rolist to not be so obvious. even ur nick is fake.

**Comment by tcptomato** [comment]
My nick is fake? I had here a profile for years with my real name on it. What exactly is fake in it?

I created a list that blocks stuff that you hypocritically ignore. Nothing more, nothing less. An ad is an ad. Not ads can be blocked as long as I don't make money from them. And what exactly did I copy?

And please don't pretend you didn't see the question: "What exactly is the threshold for blocking a banner, how many websites?". If you can't have a civilized discussion on ad-blocking, I'll stop replying, I'll consider it a waste of time.

And I'm not so sure that gorhill appreciates the fact you resurrect closed topics for some imagined insult to your honor.

**Comment by zosoro** [comment]
your nick is fake. why would a german be interested in a .ro list? come on...

1. no. you created a list that blocks banners on 3 of my sites, banners that are alrealy blocked by existing filters. there is no logic in that. 

2. you know what u copied. dont act shy now. 

3. in relation to 1, i mentioned "how many websites" to show how small-minded you are. 

4. i dont know what gorhill appreciates or not, but while he listens to bad-mouthing fake-user list-stealers, i dont really care. my email is public, he could have had a little more common sense and email me before removing the list from his plugin. those who emailled me got an explanation and things were clarified about blocked and whitelisted domains on that list.

**Comment by IDKwhattoputhere** [comment]
You are not blocking all ads on your site.

Conflict of interest => list gets removed.

**Comment by tcptomato** [comment]
1. https://ro.wikipedia.org/wiki/Germanii_din_Rom%C3%A2nia. Don't be stupid, you can google my name and find all the information on me you need. I'm on facebook and linkedin with the same "fake" name.
2. If you accuse people of something, it's customary to provide proof. 
3. No you didn't do anything. The opinion here is that all ads should be blocked. You don't agree with that. Hence you need to explain when you consider that an ad should be blocked.
4. People don't need to come to you to  ask your  thought process on blocking ads, you need to provide the rules clearly and publicly. Asking for an easy and public way to add things to the list, that wouldn't depend on your whim, is a pipe dream unfortunately.

**Comment by zosoro** [comment]
1. i can call myself Mark Zuckerberg, that dont mean i am he. 
2. at the moment i saw your list, the "banned domains" was an exact copy of mine.
3. yea, sure. go ahead and create a list to block me and act like thats not true, some people will believe you. 
4. the rules, a complain process and a suggest process is in place on apb, because the list was put in place for apb first. also people ask me to block/whitelist stuff by email. you dont know that, you just want to block ads on my blog and related sites. cause u smart and true.

**Comment by zosoro** [comment]
anyway, pointless discussion, just keep on doing what u do: badmouth me on different users and forums and cry i am unfair.

**Comment by tcptomato** [comment]
@IDKwhattoputhere Added it to my list. Thanks for reporting.

**Pull request closed without merging**
