### PR TITLE
Replace the Vietnamese filter in stock lists

### PR DESCRIPTION
**Pull request by Connor37**
The filter in the lists is outdated & not supported by Fanboy anymore.

### CODE REVIEW

**Comment by Snapy** [comment]
You should use https for `supportURL`.

**Comment by Connor37** [comment]
The support site don't use or have https protocol.

**Comment by bershan2** [comment]
@Connor37 I went to [https://abpvn.com/](https://abpvn.com/) and it loaded fine, although there is an (i) next to the URL bar (I use Chrome). Looks like the site itself has a SSL certificate, but has Non-Secure dependencies `http://i.imgur.com` and `http://fonts.googleapis.com`... but those do have SSL and even default to SSL!
Looks like a simple fix for the site admin: just replace `http:/` with `https:/` in every link. Do you know how to contact them?

**Comment by Connor37** [comment]
You can contact them through email: support@abpvn.com or through Facebook page: https://www.facebook.com/abpvn.org

**Comment by bershan2** [comment]
@Connor37 I contacted them on Facebook, it showed that they saw the message, but did not reply...

Site is reachable via HTTPS, it just is not validated as HTTPS. All content is served via HTTPS: the dependencies default to HTTPS, so the connections are upgraded right after the initial handshake. Thus I propose to hard-code support URL to `https://` and nag the developers later.

**Comment by bershan2** [comment]
@Connor37 I think it is a good idea to `squash` the two commits together, since they are modifying the **same** thing. (The git history would be clearer and would set a precedent of accepting only fully HTTPS resources.

**Comment by Connor37** [comment]
@bershan2 All commits squash.

**Comment by bershan2** [comment]
Update: The `supportURL` site only partially supports HTTPS: the main page does support HTTPS, but some pages it links to default to HTTP: e.g., [abpvn.com/ie](//abpvn.com/ie) that serves Internet Explorer users.

@gorhill Do you still consider adding this list to uBO standard subscription list (either replacing "Fanboy's Vietnamese" or adding it along side)? If so, I'll continue bugging the site owner about enabling HTTPS on other pages too.

**Comment by Connor37** [comment]
The owner actually have the github repo at https://github.com/abpvn/abpvn, I can change the `supportURL` to this one.

**Comment by bershan2** [comment]
@Connor37 The `supportURL` should lead people to the place they will get the help. In this case, it is the <https://abpvn.com>, which has some general information and a link to Facebook -- the author's preferred place for communication. The GitHub repo has only 3 issues so far.

**Comment by bershan2** [comment]
@Connor37 Since this list hasn't been added yet, I just looked at its site and have a few questions/concerns about it:
1. Under the [help section](https://abpvn.com/#ungho) the "Free support" link, "ỦNG HỘ MIỄN PHÍ", leads to ["get easy money fast" Facebook note](https://www.facebook.com/notes/b%E1%BB%99-l%E1%BB%8Dc-qu%E1%BA%A3ng-c%C3%A1o-cho-ng%C6%B0%E1%BB%9Di-vi%E1%BB%87t/ki%E1%BA%BFm-ch%C3%BAt-ti%E1%BB%81n-l%C3%BAc-r%E1%BA%A3nh-r%E1%BB%97i/1663248030564655)... weird...
2. Under the [help section](https://abpvn.com/#ungho) the ["donate" (paid support) page](https://abpvn.com/napthe), "ỦNG HỘ THẺ CÀO NHẬN LINK VIP", does not support HTTPS... and asks for credit card info, as far as I can tell. (I did not notice this at first a month ago or they changed something.)
3. The subscription link is randomly generated on a special page <https://abpvn.com/get>, while the list is hosted on GitHub `https://github.com/abpvn/abpvn/blob/master/filter/abpvn.txt`. Why would privacy-minded group track their users? Or is this just active user counter?
4. <https://filterlists.com> does not have them in the table. I'll file an issue there to add it.
5. The list is very short, I don't think it can cover the entire country's web.

**Comment by Connor37** [comment]
1. Donation by using the referral code in the app from the note, it is not about how to get easy money fast.
2. Yeah, I noticed that some of the pages don't support HTTPS, but this donate page doesn't ask for credit card info. You donate to the list maintainer through scratch cards for adding credits to your mobile plan.
3. I really don't know about this.
4. Great, this filter is support by Adguard.
5. From my experiences, the list can block any ads from any Vietnamese site, except for some sites required specific filters.

**Comment by bershan2** [comment]
@Connor37 Thanks for explanation!
Sorry for that, I used Google translate (which does not work that great). **I apologize for baseless suspicion.**
1. and 2. That's an interesting (clever) way to donate, I'll look in it more. 👍 
3. Probably we should use the GitHub URL, and tell the author that uBlock Origin and `filterlists.com` will remain uncounted for now.
4. _To be continued..._ on `filterlists.com` issue tracker.
5. I'm glad to hear that it is very efficient.

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by huh246** [comment]
cancel

**Comment by Connor37** [comment]
@gorhill Any thoughts on this so far?

**Comment by gorhill** [comment]
The commit is wrong, I have to refuse it:

- The `contentURL` is wrong, it does not point to the list itself, but rather to a GitHub HTML page from where the list can be viewed. This has to be the raw list.
- We must not replace an existing list, unless it's just a different URL for the same list.
    - The list proposed here is from a different maintainer.
    - There virtually no overlap between the list proposed here and Fanboy Vietnamese

The proper fix it to create a new entry for VIE, and remove Fanboy Vietnamese from stock filter list, since it's now labelled as "Officially unsupported".

I will do this.

**Pull request closed without merging**
