### PR TITLE
Add support for Microsoft Edge.

### PR DESCRIPTION
**Pull request by filfat**

### CODE REVIEW

**Comment by gorhill** [comment]
Best is to keep a separate repo:

- The change here would probably breaks the publishing of the extension in Chrome store, because of the unsupported keyword (`minimum_edge_version`).
- I do not really have a computer with a Windows install -- I would be unable to provide any support for it. The issue tracker could end up filled with issues I can't address.

So for now what is best is to have someone dedicated to keep a fork for the experimental support of Edge, and see how it goes from there.

**Comment by lewisje** [comment]
I don't know what kind of build process you use, but is it possible for some task-runner to inject that part of the manifest for building the Edge extension?

**Comment by gorhill** [comment]
> is it possible for some task-runner to inject that part of the manifest for building the Edge extension?

Sure, that's what the Firefox build does, take stuff from Chromium build to create `install.rdf`. The real issue here however is that I am unable to meaningfully maintain a version for Edge. Best is to spread the workload, i.e. someone maintains an upstream version of uBO for Edge, and deal with whatever issues are opened for Edge. Same for Safari.

**Comment by Benjin** [comment]
Gorhill - you want a legit Win10 key for free?  Lack of access to a Windows install seems like one of the easiest possible problem to fix.

**Comment by lewisje** [comment]
He doesn't have the time to maintain the fork himself; instead, someone who is brave enough to use Insider Previews should do it (or someone can wait until Edge extensions get into Stable).

**Comment by Hrxn** [comment]
I did not really look into this yet, but, AFAIK, extensions for Edge should be pretty similar to Chrome extensions, at least it appears that way after having a quick glance..

**Comment by lewisje** [comment]
Indeed, some of the APIs are just renamed (many of them start with "MS"), and not all Chrome Extension APIs are implemented yet, and there is this one Edge-required line in `manifest.json` that will keep the extension from building in Chrome; one part sounds like it could be handled by the `vAPI` project, but the other is a job for a task-runner.

**Comment by asuh** [comment]
This is probably wishful thinking but [Virtualbox](https://www.virtualbox.org/) is open source hypervisor where you can install a virtual machine of the latest version of [Microsoft Edge on Windows 10](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) for free. [@MSEdgeDev](https://twitter.com/MSEdgeDev) are excellent at communication and eager for feedback and suggestions. 

I'm sure I'm one of many who would love to see uBlock Origin on Edge.

**Comment by nikrolls** [comment]
FYI, I'm working on an Edge port. I have an experimental build working with a few known issues and probably some more unknown ones. Happy to accept PRs from anyone who wants to contribute, and I'll maintain it until and if @gorhill and the rest of the team feel it should be merged back into the core.

https://github.com/nikrolls/uBlock/releases/tag/1.7.7b14-edge

**Comment by gorhill** [comment]
I will be following your fork to see and comment on your issue tracker (which is not opened btw) or PRs where I see fit. Merging back into core however is impractical, since any change I make to the code base I can't test or package for Edge (I already have to ensure my changes are good for Firefox, Chromium, Chrome, Opera, Pale Moon, SeaMonkey, FF for Android, Tor).

Having a separate repo ensure code stability for the Edge version.

**Comment by Hrxn** [comment]
Since you mentioned it: [SeaMonkey](http://www.seamonkey-project.org/) hasn't released any new stable version in ages (for a browser).

So, the project looks pretty dead to me, maybe consider it as low(er) priority from now on.

**Comment by LimboSlam** [comment]
No, SeaMonkey is still very active, just no ETA yet. See this thread: http://forums.mozillazine.org/viewtopic.php?p=14623157#p14623157. As well as: https://wiki.mozilla.org/SeaMonkey/StatusMeetings/2016-05-24#2.Next, and you'll see their constant progress.

**Comment by nikrolls** [comment]
Thanks @gorhill, I'm happy to maintain it as a separate fork. I've renamed the repo to `uBlock-Edge` to make this clearer, and I've opened the issue tracker. I'll load it up with TODO items for transparency and keep you updated once it reaches a stable state.

**Comment by gorhill** [comment]
@nikrolls I am trying to understand what was required for that initial port. Was it really as simple as replacing instances of the global variable `chrome` to `browser`?

**Comment by filfat** [comment]
@gorhill Yes, most of the Chrome APIs are supported in Edge. See https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/supported-APIs/

**Comment by nikrolls** [comment]
@gorhill: That got the bulk of it working, but not all. I had to make a few more platform changes, stubbing sync for now (it's not supported in Edge yet), tweaking the `.toLocale*String()` method invocations because Edge doesn't support `'fullwide'` (this is a little hacky for now to keep it out of `src`, but the first step is to just get things working), and changing the method of generating file downloads (something about the data URI was being funny, so I used `Blob` instead). 

But to Microsoft's credit, they've done a very faithful job of implementing WebExtensions and it has been quite painless so far. Once it's stable I plan to itemise everything that needed to be changed, and any that are in `src` rather than `platform` we can discuss to see if they should/could be in the core module to make upstream merges easier.

**Comment by SylveonBottle** [comment]
As stated in my duplicate thread, and because I do not see it mentioned just yet, an update for Edge has now been made official which allows users to install extensions via the Windows Store. Pictures at #1867

**Comment by gorhill** [comment]
Development for uBO for Edge is at <https://github.com/nikrolls/uBlock-Edge/tree/1.7.7b15-edge>.

**Comment by Inverness** [comment]
I have not seen an update to the Edge fork in nearly a month. Also, it has not been published on the Windows Store.

Is there any intent to maintain that fork?

**Comment by asuh** [comment]
@Inverness He's balancing a lot. [Here's his latest update via Reddit](https://www.reddit.com/r/Windows10/comments/50ppds/any_word_on_the_ublock_origin_port_development/d760j5o).

Feel free to reach out to him yourself if you have questions, this isn't the right forum for that.

**Comment by japborst** [comment]
Regarding publishing to the store @Inverness, this is simply not possible. Will be in the future, but for now Microsoft limits it and chooses themselves whom they work together to create an extension. See the [Edge FAQ] (https://developer.microsoft.com/en-us/microsoft-edge/platform/faq/) under "I have an extension ready...".

**Comment by Akababa** [comment]
When I try to lead the extension it gives me a manifest parsing error (missing or malformed manifests file). Any fixes?

**Comment by nikrolls** [comment]
@Akababa: Pre-release Edge support is at https://github.com/nikrolls/uBlock-Edge

**Pull request closed without merging**
