### PR TITLE
Update filter syntax converter for firefox-legacy

### PR DESCRIPTION
**Pull request by JustOff**
Add additional conversion rules

Apply conversion to a wider list of filters:
- uBlockOrigin/uAssets filters
- Fanboy’s Enhanced Tracking List
- EST: Eesti saitidele kohandatud filter
- HUN: hufilter
- IDN, MYS: ABPindo
- IRN: Adblock-Iran
- NOR, DNK, ISL: Dandelion Sprouts nordiske filtre
- POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
- RUS: RU AdList

The related discussion:
http://forum.ru-board.com/topic.cgi?forum=5&topic=50113&start=3440#2

### CODE REVIEW

**Comment by JustOff** [comment]
Thank you! I would also appreciate if you let out the next point release with this update.

**Comment by gorhill** [comment]
I am trying to find out if I can create a new repo for firefox-legacy`, there is no point having a separate branch that will never be merged into master, and this currently is a burden on my side as I have to ensure no stray files end up in the package -- the auto build takes care of this in the master branch but there is no auto build for firefox legacy branch.

**Comment by gorhill** [comment]
I create a new repo for firefox legacy: <https://github.com/gorhill/uBlock-for-firefox-legacy/releases>. You should only need to point your updater to the new repo, all the rest stays the same.

**Comment by JustOff** [comment]
Thanks you, could you please consider giving this new repo a little more sweet and meaningful name, for example, uBlock-XUL?

**Comment by gorhill** [comment]
uBlock's UI never used XUL, it has always been HTML-based.

**Comment by JustOff** [comment]
Well, at least it could just be “uBlock-legacy,” as it currently targets mainly Pale Moon, SeaMonkey and Waterfox Classic, rather than older versions of Firefox.

**Comment by gorhill** [comment]
`uBlock-legacy` does not convey that it's not for Chromium-based browsers. All the browsers you mention are based on Firefox legacy technology. Back when the technology was current, though uBO happened to work for these other browsers and though I was willing to make adjustment in the code base for these other browsers, it was officially supported for Firefox only. I rather keep the name as accurate as possible.

**Comment by JustOff** [comment]
Ok, thanks for clarifying your point.

**Pull request merged**
