### PR TITLE
[mv3] Enable rulesets from manifest.json

### PR DESCRIPTION
**Pull request by m3nadav**
This bug was solved before in gorhill/uBlock@2782b16 but was reverted on gorhill/uBlock@38390ba

### CODE REVIEW

**Comment by gorhill** [comment]
See:

        if ( details.enabled ) {
            out.push(id);
            continue;
        }

**Comment by m3nadav** [comment]
I wouldn't open a PR if this was working, I promise
`getRulesetDetails` does not get the currently enabled rulesets, so it ignores the manifest.yaml-enabled rulesets

**Comment by m3nadav** [comment]
Should I expect a different behavior? should I update the rulesets/ruleset-details.json instead of the manifest.yaml?

**Comment by gorhill** [comment]
I tested all this and it works on my side. `rulesdetails.json` tells which rulesets are enabled by default (see `enabled` property). In any case, yesterday I changed to reading `declarative_net_request.rule_resources` from `manifest.json` instead -- same result but I thought reading directly from manifest was probably a lighter way to accomplish the same thing, and maybe more fork-friendly. If this doesn't work on your side, you will have to be more explicit about what exactly is not working.

---

Note that there is now a call to `patchDefaultRulesets()` at [the top of initialization](https://github.com/gorhill/uBlock/blob/1.61.3b9/platform/mv3/extension/js/background.js#L393) when a new version is launched, it's not going to properly enable the default lists if you are missing this call. The goal of that call is to 1) enable new default rulesets, 2) disable no longer default rulesets, 3) remove no longer existing rulesets.

**Comment by m3nadav** [comment]
Thanks for the details. The change you added yesterday indeed fixes the issue as it reads the manifest-enabled rulesets :)

**Pull request closed without merging**
