### PR TITLE
Use rawgit.com to download filter list

### PR DESCRIPTION
**Pull request by farrokhi**
- githubusercontent.com cannot be accessed from iran

### CODE REVIEW

**Comment by gorhill** [comment]
Thanks.

**Comment by gwarser** [comment]
I dont think this will work:

>Use a specific tag or commit hash in the URL (not a branch). Files are cached permanently based on the URL. Query strings are ignored. 

http://rawgit.com/

**Comment by lychichem** [comment]
Actually, as githubusercontent.com uses amazon S3, it's censored by Chinese GFW and not acceseble at certain time in mainland China (but no one knows when and how long it will stay in this situation)because China want all cloud service provider save files related to Chinese into servers at China and these servers must under control of Chinese corprations. Use rawgit is a good idea now.

**Comment by farrokhi** [comment]
Actually @gwarser is right. `cdn.rawgit.com` does cache permanently as they stated on the front page of their site. On the other hand `rawgit.com` does not cache the files. However it is prone to get throttled or blacklisted in case of excessive traffic. 
I am not sure what is their definition of excessive traffic and I do not have statistics from the filter file usage. I also could not find any other alternative that provides the same service without caching.
In order to be able to serve the files to Chinese or Iranian users, I believe using github.com for hosting the file is out of question. Any ideas?

**Comment by anewuser** [comment]
@rgrove

**Comment by rgrove** [comment]
I don't publicize this, but `cdn.rawgit.com` only caches `master` branch URLs for 24 hours, because too many people didn't read the docs and ended up filing support requests asking me to invalidate the cache. URLs using other branches, tags, or commit refs are cached permanently.

You're welcome to use `cdn.rawgit.com` for distributing uBlock blocklists, but I have recently heard from a user in China that it was blocked for them, so I'm not sure how useful it will be to you. I wouldn't be surprised if it was eventually blocked in Iran as well.

Definitely do not use the non-CDN `rawgit.com` for this, though. Other browser extensions have used `rawgit.com` URLs in the past and it's been a huge problem, and I've had to block them to keep the site up.

**Comment by farrokhi** [comment]
@rgrove Thank you for the clarification. This means we can use `cdn.rawgit.com` in our case (the filter is not update too often, and a 24 hour cache would't hurt). 
I believe rawgit.com is the best choice for the moment since it's always been reliable and not blocked in Iran (yet).

**Pull request merged**
