### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by ghost**
Removed Safari references. (It has been several years since any relevancy.)
Removed majority of Enterprise Deployment section. (Existing links are dead, or information provided is deprecated.)

Merged Microsoft Edge section into Chromium section for simplification. (Microsoft Edge has been Chromium-based for the last few years.)

Restructured and shortened sections, links, and explanations to make them more concise.

Rewrote sentences for better clarity and to reduce wordiness.

Fixed uBO naming conventions.
Fixed spelling and grammar issues.
Fixed coding and formatting issues.
Fixed consistency issues.

Updated names as needed.
Updated section header titles as needed.
Updated URLs.

Other minor fixes.

### CODE REVIEW

**Comment by ghost** [comment]
@gorhill,

I have improved the README.md. Can you please take a look?

**Comment by gorhill** [comment]
Personally I would remove the "Pronounced ..." section, I think it came to be at a time when I changed `µ` to `u` and this needed clarification. At this point the name is brand-level and there is no need to explain it.

**Comment by ghost** [comment]
Sure, just give me a moment.

**Comment by ghost** [comment]
I have removed the pronunciation section as you requested. Any other ideas or feedback?

**Comment by ghost** [comment]
Also, how do you feel about the Firefox Legacy section and the Debian section?

I don't know how accurate, relevant, or up-to-date the Debian section is or if it still even applies today.

**Comment by gorhill** [comment]
We can remove Debian/Firefox legacy details from the readme. The "[Manual Installation](https://github.com/gorhill/uBlock/tree/master/dist#install)" link contains information for both Chromium and Firefox so it should not appear specific to any of these (it's currently under "Chromium" section). If need to be, more details about Debian/Firefox legacy could be added to the"Manual installation" page itself in the future.

**Comment by ghost** [comment]
Sure, let me work on that real quick.

**Comment by ghost** [comment]
I removed the Firefox Legacy & Debian sections and their applicable links.

While I was going through the table of contents, I noticed some inconsistencies and some other sections that could be added for more uniformity,

I renamed the Philosophy section to General Information. I just chose something that was consistent between the table of contents and the existing section header title. How do you feel about this change? I can definitely change it back to Philosophy and also the associated changes I just made. I just wanted consistency between the names in the table of contents and the section header titles.

**Comment by gorhill** [comment]
All look good to me, thanks.

**Pull request merged**
