### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by mjethani**
Described here: https://github.com/uBlockOrigin/uBlock-issues/issues/1664#issuecomment-890339567

### CODE REVIEW

**Comment by gorhill** [comment]
The command `make ./node_modules/uBO-snfe` in cliqz repo fails on my side. I get the following error:

    npm install dist/build/uBlock0.nodejs.tgz --no-save
    npm ERR! code ENOPACKAGEJSON

When I look at the content of `dist/build/uBlock0.nodejs.tgz`, the root directory is `dist`, hence I guess why npm complain of not finding `package.json`.

**Comment by mjethani** [comment]
>… the root directory is `dist`

This is why I have `--strip-components 2` as an option to `tar`. Maybe it doesn't work on Linux too? Because everything I've tested is on macOS.

**Comment by gorhill** [comment]
I changed to the following on my side and this worked:

    dist/build/uBlock0.nodejs.tgz: dist/build/uBlock0.nodejs
	    tar -C ./dist/build -czf dist/build/uBlock0.nodejs.tgz uBlock0.nodejs

Does this work for you?

**Comment by gorhill** [comment]
Another issue with the benchmark is that on my side I need to replace:

    const modulePromise = import('ubo-snfe');

With

    const modulePromise = import('uBO-snfe');

For it to run successfully.

**Comment by mjethani** [comment]
>Does this work for you?

It works.

Maybe the most portable is`cd dist/build && tar czf uBlock0.nodejs.tgz`.

>Another issue with the benchmark is …

That makes sense, my filesystem is case-insensitive. In that case, could you submit a patch?

**Comment by gorhill** [comment]
> could you submit a patch?

Sure but that will have to wait for tomorrow on my side. Feel fee to submit if you feel for it.

**Comment by mjethani** [comment]
Package names [must be lowercase](https://blog.npmjs.org/post/168978377570/new-package-moniker-rules.html):

>You can't create new packages with upper-case letters in the name any more, but packages with upper-case letters in their names are still in the registry and still in use.

Let me submit patches to fix this is both places.

**Comment by gorhill** [comment]
Is the following modification ok or is there a better way to accomplish this?

```makefile
dist/build/uBlock0.nodejs: tools/make-nodejs.sh $(sources) $(platform) $(assets)
	tools/make-nodejs.sh
```

I modified the content of `tools/make-nodejs.sh` just to add a few more `js` files for the sake of testing them for `eslint` warnings, but since the target is not dependent on the script itself used to build them, I had to use `-B` to force a built. Adding a dependency on the build script would fix this.

**Comment by mjethani** [comment]
>Adding a dependency on the build script would fix this.

I think this makes sense.

**Comment by mjethani** [comment]
If you do it though it's best to do it for Chromium and Firefox too.

**Pull request merged**
