### PR TITLE
Dashboard unsaved warning (https://github.com/uBlockOrigin/uBlock-issues/issues/145)

### PR DESCRIPTION
**Pull request by jspenguin2017**
https://github.com/uBlockOrigin/uBlock-issues/issues/145

---

Unsaved change warning for all tabs are now implemented. 

The self-destructing mechanism of `uDom` is removed.

### CODE REVIEW

**Comment by gorhill** [comment]
> Can the self-destructing mechanism of `uDom` be removed?

Yes. I can't remember exactly why I put that it, I think it had to do with trying to avoid memory leaks early in development -- but that shouldn't be an issue when the document is unloaded. On a more general note I also want to avoid uDom now, except where it's really convenient, i,e, where there is no straightforward plain DOM methods equivalent.

**Comment by gorhill** [comment]
How do I squash and merge into a new branch so that I can try this on my side without modifying master?

**Comment by gwarser** [comment]
https://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github

**Comment by gorhill** [comment]
I don't have that button on my side.

a

**Comment by gorhill** [comment]
Never mind, found the extra command line instructions aside the "Squash and merge" button:

>     git checkout -b jspenguin2017-master master
>     git pull https://github.com/jspenguin2017/uBlock.git master

**Comment by jspenguin2017** [comment]
You can get patch file here: https://patch-diff.githubusercontent.com/raw/gorhill/uBlock/pull/3730.patch

Just apply that to your local copy, and `git reset --hard` when you're done.

**Comment by jspenguin2017** [comment]
Should be good now, I tested everything.

**Pull request closed without merging**
