### PR TITLE
block email-open-tracking pixel from mailfoogae.appspot.com

### PR DESCRIPTION
**Pull request by paulasmuth**

### CODE REVIEW

**Comment by gorhill** [comment]
The content of all uBlock's filters are for cases I can verify myself, I can't add stuff I have not confirmed myself. Also, whenever one of these filter lists is modified, the uBO's checksums.txt file must be recomputed.

**Comment by IDKwhattoputhere** [comment]
You should contact an EasyPrivacy author. I guess you got two options here:
https://adblockplus.org/en/getting_started#false-negatives
https://forums.lanik.us/

**Comment by saintleon** [comment]
can i get help with this please

**Comment by gorhill** [comment]
Report to <https://forums.lanik.us/viewforum.php?f=62>.

**Pull request closed without merging**
