### PR TITLE
CSS cleanup

### PR DESCRIPTION
**Pull request by timse201**
there should be no visible change

many doubled css styles and default values etc. and some which can be combined

### CODE REVIEW

**Comment by 2017-05-1200-11-20** [comment]
@@[https://github.com/gorhill/uBlock/pull/2820/commits/b51bfd33ce97535e235577716ea871879f236c6c]

**Comment by 2017-05-1200-11-20** [comment]
Hi, 
It work?

**Comment by 2017-05-1200-11-20** [comment]
Ｏｏｏ－ｏｐｓ ｉｔ ｗｏｒｋ， ｉ ｄｉｓｃｏｎｎｅｃｔ ｍｙ ｓｈａｒｅ ＶＰＮ ．．．

**Comment by 2017-05-1200-11-20** [comment]
timse201:patch-1⊥set: ＃２８２０

**Comment by s-uds** [comment]
All those commits with the same message repeated ("cleanup", etc.) should be squashed into one.

**Pull request closed without merging**
