### PR TITLE
Add `env_legacy` to the pre-processor supported tokens

### PR DESCRIPTION
**Pull request by JustOff**
This will allow specifically target uBlock Origin for Firefox legacy-based browsers in shared filter lists,
see https://github.com/gorhill/uBlock-for-firefox-legacy/pull/1.

### CODE REVIEW

**Comment by gorhill** [comment]
Is there a need for this? What filter requires such conditional token?

**Comment by JustOff** [comment]
Having `env_legacy` defined everywhere is required to be able to use the following syntax:

```
!#if env_firefox
!#if !env_legacy
...
!#endif
!#endif
```

because in https://github.com/gorhill/uBlock-for-firefox-legacy/pull/1 we set `env_firefox = true` for uBO-legacy.

Of course, this can only be used after both mainline and uBO-legacy releases are widely distributed.

**Comment by gorhill** [comment]
I rather not have code in uBO for which the case has not been made yet, there has to be a case made for it. I accepted the PR for <https://github.com/gorhill/uBlock-for-firefox-legacy> because for this repo I will accept PRs without testing and assume that it's tested, and needed. I rather discourage filter list maintainers from burdening themselves with having to maintain yet-another platform in officially supported filter lists. Filters requiring `env_legacy` should be maintained in their own specific filter lists.

**Comment by JustOff** [comment]
Well, to be honest, this is quite disappointing. There are `env_edge` and `env_safari` tokens, while the first one is basically equals to `env_chromium` now, and the second one is for the two years old add-on with no prospects. Against this background, do you really see any critical flaws in using `env_legacy` in general filters, while filter list maintainers agree to support uBO-legacy?

**Comment by gorhill** [comment]
I am more opened to remove unused `env_edge`/`env_safari` tokens than add an additional token which usefulness has not been demonstrated yet.

**Comment by JustOff** [comment]
> Filters requiring `env_legacy` should be maintained in their own specific filter lists.

Unfortunately, for regional subscriptions it's quite inconvenient to do so just for uBO-legacy.

> an additional token which usefulness has not been demonstrated yet

Well, I found an example: if `env_legacy` existed, [this mess](https://github.com/uBlockOrigin/uAssets/commit/ba09035af81633142934ed9e15d177bd743dc72d) could have been easily avoided.

And I'm sure that there will be more such examples after uBO-legacy starts accepting the rules for `env_firefox`, however by that time, if we do not already have `env_legacy` in the widespread uBO version, it will be much more difficult to deal with it.

We, users of uBO-legacy are very grateful that the filter-list maintainers (@okiehsch, @mapx- and others) are paying attention to our problems, and having `env_legacy` will only make their work easier.

**Comment by gorhill** [comment]
> if env_legacy existed, this mess could have been easily avoided.

That's a good example, so I will accept the PR.

**Comment by gorhill** [comment]
Thanks.

**Comment by JustOff** [comment]
Thank you for being truly open-minded and receptive to arguments, I really appreciate that.

**Pull request merged**
