### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ghost**
Completely revamped and expanded document.

### CODE REVIEW

**Comment by ghost** [comment]
@gorhill

I have completely redone the CONTRIBUTING.md.

Do you have any feedback or ideas on what needs adding, removing, or expanding in this document?

Can you think of other ways people can contribute/help with the project not already mentioned that need adding to this document?

Thank you

**Comment by gorhill** [comment]
uBO Legacy is not really maintained anymore, I wouldn't want to give the impression the project is still maintained. It was maintained by @JustOff (just one of [his countless contributions](https://justoff.github.io/)), who is Ukrainian, and hasn't been active since Feb. 18, 2022.

**Comment by ghost** [comment]
@gorhill

OMFG! LOL! I was literally just crafting a list of reasons and questions about removing all references and information about uBO Legacy in the different repositories.

We must be on the same mental wave length right now!!! :rofl:

**Comment by ghost** [comment]
@gorhill

So I take your comment as confirmation to remove all references and information about uBO Legacy at least when it comes to documents like the README.md, Bug Report Templates, this document, etc...

But, not necessarily when it comes to the Wiki.

**Pull request merged**
